SolarPower:
  carbon_intensity: 30
  marginal_cost: 0
  color: "#EE8845"
WindPower:
  carbon_intensity: 13
  marginal_cost: 0
  color: "#86D2C2"
GasPower:
  carbon_intensity: 501
  marginal_cost: 200
  installed_capacity: 12800
  color: "#BF486D"
CoalPower:
  carbon_intensity: 954
  marginal_cost: 250
  installed_capacity: 1820
  color: "#B89E55"
BiomassPower:
  carbon_intensity: 230
  marginal_cost: 100
  installed_capacity: 2230
  color: "green"
NuclearPower:
  carbon_intensity: 5
  marginal_cost: 50
  installed_capacity: 64000
  color: "#BAC039"
HydroPower:
  carbon_intensity: 11
  marginal_cost: 20
  color: "#4585B8"
  installed_capacity: 11514
ReservoirHydroPower:
  carbon_intensity: 11
  marginal_cost: 250
  installed_capacity: 8787
  color: "#4585EE"
StoredHydroPower:
  carbon_intensity: 67
  marginal_cost: 250
  installed_capacity: 5064
ImportedPower:
  carbon_intensity: 200
  marginal_cost: 1000
  installed_capacity: 10000
  color: "gray"